config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :find_flat, only: %i[edit show update destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guest)
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
    <%= simple_form_for @flat do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guest %>
      <%= f.submit "Submit", class: "btn btn-primary", method: :patch  %>
    <% end %>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
      <div class="col-md-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url('https://images.pexels.com/photos/2459/stairs-home-loft-lifestyle.jpg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;w=500')"></div>
          <div class="flat-card-content">
            <div class="flat-card-title">
              <%= @flats.each do |flat| %>
                <h4><%= flat.name %></h4>
            </div>
            <div class="address">
              Address:
            </div>
            <%= flat.address %>
            <div class="price">
              Price a night
            </div>
            <%= flat.price_per_night %>
            <div class="guest">
            Maximum guest
            </div>
            <%= flat.number_of_guest %>
            <div class="moreInfo">
              <%= link_to 'More info', flat_path(flat) %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
</div>

app/views/flats/new.html.erb
<div class="container">
    <%= simple_form_for @flat do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guest %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1><%= @flat.name %></h1>
  <%= @flat.description %>
  <%= @flat.name %>
  <%= @flat.address %>
  <%= @flat.price_per_night %>
  <%= @flat.number_of_guest %>
  <%= link_to "Edit '#{@flat.name}'", edit_flat_path(@flat) %>
  <%= link_to "Remove '#{@flat.name}'", flat_path(@flat), method: :delete ,
            data: { confirm: "Are you sure?" }%>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/flats/">Simple Airbnb</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="ms-auto flex">
            <form class="flex my-2 my-lg-0">
              <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <a class="btn btn-outline-primary my-2 my-sm-0 ms-2" href="/flats/new">Add Flat</a>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>